apiVersion: v1
entries:
  onebe:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-05-03T10:01:27.5045012+07:00"
    description: A Helm chart for my onebe app
    digest: 606d7047caeaa89b1b10892aa07e804e32438f6db1d8e24c45c347412287adc3
    name: onebe
    type: application
    urls:
    - https://github.com/thongdq/OneBe/onebe-1.0.0.tgz
    version: 1.0.0
generated: "2023-05-03T10:01:27.5039958+07:00"
