version: "3.8"
services:
  postgresdb:
    image: postgres:15.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - "5433:5432"
    volumes:
      - postgresqldb:/var/lib/postgresql/data
  projectonebe:
    depends_on:
      - postgresdb
    build: ./
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - .m2:/root/.m2
volumes:
  postgresqldb:
