spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/testdb"
    username: "postgres"
    password: "root"
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: "none"
  liquibase:
    change-log: classpath:db\changelog\db.changelog-master.yaml

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# App Properties
onebe:
  app:
    jwtSecret: "onebeSecretKey"
    jwtExpirationMs: 60000
    jwtRefreshExpirationMs: 120000
