apiVersion: apps/v1
kind: Deployment
metadata:
  name: onebe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onebe-app
  template:
    metadata:
      labels:
        app: onebe-app
    spec:
      containers:
        - image: thongdq/projectone-be-img
          name: onebe-app
          command:
            [
              "java",
              "-jar",
              "-Dspring.profiles.active=k8s",
              "projectone-0.0.1-SNAPSHOT.jar",
            ]

          ports:
            - containerPort: 8080
