apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-claim
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "G:\\dqt\\project1\\be\\OneBe\\k8s\\docker\\data"
